version: '2'
networks:
  backend:
    external:
      name: rpicaddy_backend

services:
  invitation:
    image: hypriot/rpi-busybox-httpd  
    restart: always
    volumes:
      - $PWD/site:/www
    networks:
      - backend
    expose:
      - 80
