version: "2"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  caddy:
    build: .
    #restart: always
    networks:
      - frontend
      - backend 
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    volumes:
      - ./site:/srv
      #- ./config/Caddyfile:/etc/Caddyfile
      - ./config:/root/.caddy
    command: --agree --conf /root/.caddy/Caddyfile
