version: "2"

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

services:
  caddy:
    build: .
    restart: always
    networks:
      - frontend
      - backend 
    ports:
      - 141.13.92.71:80:80
      - 141.13.92.71:443:443
      - 141.13.92.71:2015:2015
    volumes:
      - ./site:/srv
      - ./config:/root/.caddy
    command: --agree --conf /root/.caddy/Caddyfile

  ui:
    image: hypriot/rpi-dockerui
    restart: always
    ports:
      - 9000
    privileged: true
    networks:
      - backend 
    command: -e http://192.168.9.1:2378
